[workspace]
default-members = ["kmip", "ttlv", "ttlv-derive"]
resolver = "3"
members = ["kmip", "ttlv", "ttlv-derive"]

[workspace.package]
publish = false
repository = "https://github.com/phsym/kmip-rs"
rust-version = "1.88.0"
authors = ["Pierre-Henri Symoneaux"]
edition = "2024"
version = "0.2.0"
license = "MIT OR Apache-2.0"
